### ISSUE TITLE
defrecord values colliding with clojure.core functions

### ISSUE THREAD

**Issue by andrusieczko** [dakrone/lein-bikeshed#21]
Hi,

I've got a defrecord defined as follows:

```
(defrecord Query [sort limit start])
```

Unfortunately, this gives me:

```
Checking for arguments colliding with clojure.core functions.
#'com.my-domain.core.query/->Query: 'sort' is colliding with a core function
```

Is this a desirable behaviour? `sort` here is a keyword rather than a variable / function name.

If I wrote:

```
(defprotocol Q (get-sort [this]))
(defrecord Query [sort limit start]
  Q
  (get-sort [this] sort))
```

then I understand it's incorrect of course.

How can I workaround it without changing the name of `:sort`?

Thanks,
Karol

**Comment by dakrone** [comment]
> Is this a desirable behaviour? sort here is a keyword rather than a variable / function name.

I think it's still desirable behavior because `sort` could be a map here, in which case calling something like `(sort :foo)` is confusing (sort as a map or sort as a core function).

**Comment by andrusieczko** [comment]
Hmm, point taken.

I'll close the issue then, it's convincing enough :) Thanks!
