### ISSUE TITLE
Place explicit dependency on clojure.tools.cli

### ISSUE THREAD

**Issue by vemv** [dakrone/lein-bikeshed#33]
Hi!

I use (and have to use) `[org.clojure/tools.namespace "0.3.0-alpha4"]` and `[org.clojure/tools.reader "1.1.0"]`.

I reckon they depended on clojure.tools.cli at some point, which is why you don't depend on it in your project.clj. So I get: 

```
Caused by: java.io.FileNotFoundException: Could not locate clojure/tools/cli__init.class or clojure/tools/cli.clj on classpath.
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate clojure/tools/cli__init.class or clojure/tools/cli.clj on classpath., compiling:(leiningen/bikeshed.clj:1:1)
```

Of course, I could fix by depending on `[org.clojure/tools.cli "0.3.5"]` myself.

Just a heads up 🙌

Cheers - Victor

**Comment by gonewest818** [comment]
I have the same file not found exception.  It looks to me like pull request #31 deleted org.clojure/tools.cli from project.clj, but there's still a :require in the leiningen.bikeshed ns here: https://github.com/dakrone/lein-bikeshed/blob/master/src/leiningen/bikeshed.clj#L3
