### ISSUE TITLE
Portability and (ba)sh coupling (Windows Powershell)

### ISSUE THREAD

**Issue by clojens** [dakrone/lein-bikeshed#4]
While forced to use my GF's laptop with Winblows, using Powershell, I noticed that `bikeshed` relies on `sh` to be present on the platform and, since I wasn't using Cygwin, fails to do so on a 'pure' Windows system. 

Is there any special need for the heavy reliance on sh? Wouldn't a full Clojure (file reader) solution make more sense perhaps? At least it would seem a more portable solution but I'm keen to learn more on your design considerations and argumentation for/against.

If desirable, I could write it if you'd like or take it up yourself if you want, or just reject the idea altogether should this make no sense :)

**Comment by dakrone** [comment]
Resolved by #31
